Add missing comma in common.py
Or else I get this error:

Traceback (most recent call last):                                                                                                                    
  File "/usr/lib/webapp-manager/webapp-manager.py", line 25, in <module>
    from common import _async, idle, WebAppManager, Browser, download_favicon, ICONS_DIR, BROWSER_TYPE_FIREFOX
  File "/usr/lib/webapp-manager/common.py", line 213
    Browser(BROWSER_TYPE_CHROMIUM, "Brave (Flatpak)", ".local/share/flatpak/exports/bin/com.brave.Browser", ".local/share/flatpak/exports/bin/com.brave.Browser")

SyntaxError: invalid syntax. Perhaps you forgot a comma?